baseURL = "https://console.dev"
languageCode = "en-us"
title = "Console"
theme = "console-home"
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
rssLimit = 10
assetDir = "assets"

disableKinds = ["taxonomy", "term"]

[taxonomies]
    category = "categories"
    tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true

[outputs]
home = [ "HTML" ]
section = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[params]
consoleSubscribers = "18k+"
consolePodcastTitle = "Observability, with Charity Majors"
consolePodcastURL = "https://cdn.simplecast.com/audio/10488ddf-3ca4-4300-9391-c2967d806334/episodes/8e88affe-5a27-4755-875d-5f2947bc5bbb/audio/1865a097-033b-478c-8037-7f2883098ade/default_tc.mp3?aid=rss_feed&feed=T80CJwln"
#forceNewsletterDate = "" # YYYY-MM-DD
#returnNewsletterDate = "" # YYYY-MM-DD
