baseURL = "https://console.dev"
languageCode = "en-us"
title = "Console"
theme = "console-home"
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
rssLimit = 10
assetDir = "assets"

disableKinds = ["taxonomy", "term"]

[taxonomies]
    category = "categories"
    tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true

[outputs]
home = [ "HTML" ]
section = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[params]
consoleSubscribers = "18k+"
consolePodcastTitle = "Decentralization, with Brooklyn Zelenka"
consolePodcastURL = "https://cdn.simplecast.com/audio/10488ddf-3ca4-4300-9391-c2967d806334/episodes/21114878-64c4-4605-95ba-81c946feaa77/audio/32a8188f-0a02-4847-95f8-b8f007ef3a34/default_tc.mp3?aid=rss_feed&feed=T80CJwln"
#forceNewsletterDate = "" # YYYY-MM-DD
#returnNewsletterDate = "" # YYYY-MM-DD
