baseURL = "https://console.dev"
languageCode = "en-us"
title = "Console"
theme = "console-home"
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
rssLimit = 10
assetDir = "assets"

disableKinds = ["taxonomy", "term"]

[taxonomies]
    category = "categories"
    tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true

[outputs]
home = [ "HTML" ]
section = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[params]
consoleSubscribers = "18k+"
consolePodcastTitle = "Devtools investing, with Ed Sim (Boldstart)"
consolePodcastURL = "https://cdn.simplecast.com/audio/10488ddf-3ca4-4300-9391-c2967d806334/episodes/72a312a7-0768-4faa-a902-3bf9b9634fd0/audio/5fce0eb5-f702-49b3-abf4-a78c89e2d00c/default_tc.mp3?aid=rss_feed&feed=T80CJwln"
#forceNewsletterDate = "" # YYYY-MM-DD
#returnNewsletterDate = "" # YYYY-MM-DD
