baseURL = "https://console.dev"
languageCode = "en-us"
title = "Console"
theme = "console-home"
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
rssLimit = 10
assetDir = "assets"

disableKinds = ["taxonomy", "term"]

[taxonomies]
category = "categories"
tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true

[outputs]
home = ["HTML"]
section = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"

[params]
consoleSubscribers = "26k+"
# For the annual end of year countdown, set the forceNewsletterDate to the last
# newsletter date of the year and the returnNewsletterDate to the first
# newsletter date of the next year. Comment out when not in use.
#forceNewsletterDate = "2022-12-15"  # YYYY-MM-DD
#returnNewsletterDate = "2023-01-05" # YYYY-MM-DD
