baseURL = "https://console.dev"
languageCode = "en-us"
title = "Console"
theme = "console-home"
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
rssLimit = 10

disableKinds = ["taxonomy", "term"]

[taxonomies]
    category = "categories"
    tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":git", "date", "publishDate"]

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true

[outputs]
home = [ "HTML" ]
section = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
