name = "home"
type = "webpack"
account_id = "e7764905d1562eb381bdbef888ca7a92"
zone_id = "a231ab8a31380c1d3d664b11d1d459cb"
vars = { ENVIRONMENT = "test" }

[env.production]
vars = { ENVIRONMENT = "production" }
route = "https://console.dev/*"

[env.test]
vars = { ENVIRONMENT = "test" }
workers_dev = true

[env.perftest]
vars = { ENVIRONMENT = "test" }
workers_dev = true

[site]
bucket = "./public"
