# Compress images on demand (workflow_dispatch) and 4pm every day.
# Open a Pull Request if any images can be compressed.
name: Compress images (cron/manual)
on:
    workflow_dispatch:
    schedule:
        - cron: "00 16 * * WED"
jobs:
    build:
        name: calibreapp/image-actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Compress Images
              id: calibre
              uses: calibreapp/image-actions@main
              with:
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  compressOnly: true
                  # https://github.com/calibreapp/image-actions#ignore-paths
                  # The Sourcegraph logo get compressed down to really poor
                  # quality for some reason, so exclude it
                  ignorePaths: "static/img/favicons/about.sourcegraph.com.png,static/img/favicons/sourcegraph.com.png"

            - name: Create New Pull Request If Needed
              if: steps.calibre.outputs.markdown != ''
              uses: peter-evans/create-pull-request@v3.12.0
              with:
                  title: Compressed Images
                  branch-suffix: timestamp
                  commit-message: Compressed Images
                  body: ${{ steps.calibre.outputs.markdown }}
