name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <production|test>'
        required: true
        default: 'test'

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@v2

            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: ${{ github.event.inputs.environment }}
