name: Run perf tests

on:
  push

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: perftest

      - name: Run k6 test
        uses: k6io/action@v0.2.0
        with:
          filename: tests/perf.js
