name: Run k6 tests

on: push

jobs:
    k6_load_test:
        name: k6 Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: "hugo build"
              uses: jakejarvis/hugo-build-action@v0.97.0

            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: test

            # Allows Cloudflare deploy to propagate
            - name: Sleep for 10 seconds
              run: sleep 10s
              shell: bash

            - name: k6 test (home)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/home.js
              env:
                  CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
                  CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}

            - name: k6 test (tools)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/tools.js
              env:
                  CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
                  CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}

            - name: k6 test (betas)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/betas.js
              env:
                  CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
                  CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}

            - name: k6 test (podcast-s02e01)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/podcast-s02e01.js
              env:
                  CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
                  CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
