name: Run perf tests

on: push

jobs:
    k6_load_test:
        name: k6 Load Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: "hugo build"
              uses: jakejarvis/hugo-build-action@v0.84.0

            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: perftest
                  wranglerVersion: "1.15.0"

            - name: k6 test (home)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/home.js

            - name: k6 test (betas)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/betas.js

            - name: k6 test (tools)
              uses: k6io/action@v0.2.0
              with:
                  filename: tests/tools.js
